<?php

/*
 * Add the digital post btn to the wysiwig plugin.
 * At the moment only CKeditor is supportet.
 */
function oc_digipost_wysiwyg_plugin($editor, $version) {

  drupal_add_js(array('oc_digipost' => array('oc_digipost_url' => variable_get('oc_digipost_url','http://borger.dk/'),
      'oc_digipost_mailboxids' => variable_get('oc_digipost_mailboxid',''),
      'oc_digipost_btntext' => variable_get('oc_digipost_btntext','')
      )), 'setting');
  
  switch ($editor) {
   case 'ckeditor':
    return array(
     'oc_digitpost_plugin' => array(
      'path' => drupal_get_path('module', 'oc_digipost') . '/plugins/ckeditor',
      'buttons' => array(
       'oc_digitpost_button' => t('Digital Post'),
      ),
      'load' => TRUE,
     ),
    );
    break;
  }
 }
 /*
  * Backend config.
  */
 function oc_digipost_admin() {
  $form = array();
  //The url to the digital post provider ( always borger.dk/post? )
  $form['oc_digipost_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Digital URL'),
    '#default_value' =>  variable_get('oc_digipost_url','https://borger.dk/post?') ,
    '#size' => 50,
    '#description' => t("DigitalPos Mailbox id."),
    '#required' => TRUE,
  );
  /*
   * The mailbox id of the organisation/user that  should recieve the email.
   */
  $form['oc_digipost_mailboxid'] = array(
    '#type' => 'textfield',
    '#title' => t('Mailbox id'),
    '#default_value' => variable_get('oc_digipost_mailboxid',''),
    '#size' => 50,
    '#description' => t("DigitalPos Mailbox id."),
    '#required' => TRUE,
  );
   /*
   * The text to be used in the markup generation for labeling.
   */
  $form['oc_digipost_btntext'] = array(
    '#type' => 'textfield',
    '#title' => t('Link text'),
    '#default_value' => variable_get('oc_digipost_btntext','Skriv til os'),
    '#size' => 50,
    '#description' => t("Link text"),
    '#required' => TRUE,
  );
  
  return system_settings_form($form);
}
/*
 * Setup menu.
 */
function oc_digipost_menu() {
  $items = array();
  $items['admin/settings/oc_digitalpost'] = array(
    'description' => 'Configuration af oc digitalpost modul',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oc_digipost_admin'),
    'access arguments' => array('administer oc_digipost'),
   );
  return $items;
}
/**
 * Implements hook_permission().
 */
function oc_digipost_permission() {
  return array(
    'administer oc_digipost' => array(
      'title' => t('Administrer digitalpost'),
      'description' => t('Giver adgang til configuere digitalpost'),
    )
  );
}
/*
 * Set default permissions to admin only.
 */
function oc_digipost_enable() {
  $admin_role = user_role_load_by_name('administrator');
  // Additional permissions.
  user_role_grant_permissions($admin_role->rid, array(
    'administer oc_digipost' => TRUE
  ));
}


